/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLIENT_H_RPCGEN
#define _CLIENT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct planeListRet {
	int err;
	union {
		airports *head;
	} planeListRet_u;
};
typedef struct planeListRet planeListRet;

struct airports {
	char *acr;
	char *name;
	float lon;
	float lat;
	struct airports *next;
};
typedef struct airports airports;

struct location {
	char *city;
	char *state;
};
typedef struct location location;

#define CLIENT 0x36459328
#define CLIENT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getPlaceAirports 1
extern  planeListRet * getplaceairports_1(location *, CLIENT *);
extern  planeListRet * getplaceairports_1_svc(location *, struct svc_req *);
extern int client_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getPlaceAirports 1
extern  planeListRet * getplaceairports_1();
extern  planeListRet * getplaceairports_1_svc();
extern int client_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_planeListRet (XDR *, planeListRet*);
extern  bool_t xdr_airports (XDR *, airports*);
extern  bool_t xdr_location (XDR *, location*);

#else /* K&R C */
extern bool_t xdr_planeListRet ();
extern bool_t xdr_airports ();
extern bool_t xdr_location ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLIENT_H_RPCGEN */
