/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "client.h"

planeListRet *
getplaceairports_1_svc(location *argp, struct svc_req *rqstp)
{
	static planeListRet  result;

	/*
	 * insert server code here
	 */

	return &result;
}
