/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "client.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

planeListRet *
getplaceairports_1(location *argp, CLIENT *clnt)
{
	static planeListRet clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, getPlaceAirports,
		(xdrproc_t) xdr_location, (caddr_t) argp,
		(xdrproc_t) xdr_planeListRet, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
