# This is a template Makefile generated by rpcgen

# Parameters

PLANE = plane_client
PLACES = places_server
AIRPORTS = airports_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = plane.x places.x  

PLANE_SVC.c = plane_svc.c plane_server.c plane_xdr.c  
PLANE_CLNT.c = plane_clnt.c plane_client.c plane_xdr.c
PLANE_TARGETS = plane.h plane_xdr.c plane_clnt.c plane_svc.c plane_client.c plane_server.c

PLACES_SVC.c = places_svc.c places_server.c places_xdr.c   
PLACES_CLNT.c = places_clnt.c places_client.c places_xdr.c
PLACES_TARGETS = places.h places_xdr.c places_clnt.c places_svc.c places_client.c places_server.c

OBJECTS_PLANE_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(PLANE_CLNT.c:%.c=%.o)
OBJECTS_PLANE_SVC = $(SOURCES_SVC.c:%.c=%.o) $(PLANE_SVC.c:%.c=%.o)

OBJECTS_PLACES_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(PLACES_CLNT.c:%.c=%.o)
OBJECTS_PLACES_SVC = $(SOURCES_SVC.c:%.c=%.o) $(PLACES_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl
RPCGENFLAGS = 

# Targets 

all : $(PLANE) $(PLACES)

$(OBJECTS_PLANE_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(PLANE_CLNT.c) 

$(OBJECTS_PLANE_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(PLANE_SVC.c) 

$(PLANE) : $(OBJECTS_PLANE_CLNT) 
	$(LINK.c) -o $(PLANE) $(OBJECTS_PLANE_CLNT) $(LDLIBS) 

$(PLACES) : $(OBJECTS_PLANE_SVC) 
	$(LINK.c) -o $(PLACES) $(OBJECTS_PLANE_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(PLANE_TARGETS) $(OBJECTS_PLANE_CLNT) $(OBJECTS_PLANE_SVC) $(PLANE) $(PLACES)


all : $(PLACES) $(AIRPORTS)

$(OBJECTS_PLACES_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(PLACES_CLNT.c) 

$(OBJECTS_PLACES_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(PLACES_SVC.c) 

$(PLACES) : $(OBJECTS_PLACES_CLNT) 
	$(LINK.c) -o $(PLACES) $(OBJECTS_PLACES_CLNT) $(LDLIBS) 

$(AIRPORTS) : $(OBJECTS_PLACES_SVC) 
	$(LINK.c) -o $(AIRPORTS) $(OBJECTS_PLACES_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(PLACES_TARGETS) $(OBJECTS_PLACES_CLNT) $(OBJECTS_PLACES_SVC) $(PLACES) $(AIRPORTS)

