/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 500

typedef char *portInfo;

typedef char *placeInfo;

#ifndef AIRPORTS
#define AIRPORTS
struct airports {
	placeInfo p;
	portInfo port1;
	portInfo port2;
	portInfo port3;
	portInfo port4;
	portInfo port5;
};
typedef struct airports airports;
#endif

#ifndef LISTRET
#define LISTRET
struct planeListRet {
	int err;
	union {
		airports airp;
	} planeListRet_u;
};
typedef struct planeListRet planeListRet;
#endif

struct position {
	double lon;
	double lat;
};
typedef struct position position;

#define AIRPORT_LOOKUP_PROG 0x26459329
#define AIRPORT_LOOKUP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define QUERY_AIRPORTS 1
extern  planeListRet * query_airports_1(position *, CLIENT *);
extern  planeListRet * query_airports_1_svc(position *, struct svc_req *);
extern int airport_lookup_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define QUERY_AIRPORTS 1
extern  planeListRet * query_airports_1();
extern  planeListRet * query_airports_1_svc();
extern int airport_lookup_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_portInfo (XDR *, portInfo*);
extern  bool_t xdr_placeInfo (XDR *, placeInfo*);
extern  bool_t xdr_airports (XDR *, airports*);
extern  bool_t xdr_planeListRet (XDR *, planeListRet*);
extern  bool_t xdr_position (XDR *, position*);

#else /* K&R C */
extern bool_t xdr_portInfo ();
extern bool_t xdr_placeInfo ();
extern bool_t xdr_airports ();
extern bool_t xdr_planeListRet ();
extern bool_t xdr_position ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
