/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct planeListRet {
	int err;
	union {
		airports *head;
	} planeListRet_u;
};
typedef struct planeListRet planeListRet;

struct airports {
	char *acr;
	char *name;
	float lon;
	float lat;
	struct airports *next;
};
typedef struct airports airports;

struct position {
	float lon;
	float lat;
};
typedef struct position position;

#define PLACES 0x26459329
#define PLACES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getAirports 1
extern  planeListRet * getairports_1(position *, CLIENT *);
extern  planeListRet * getairports_1_svc(position *, struct svc_req *);
extern int places_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getAirports 1
extern  planeListRet * getairports_1();
extern  planeListRet * getairports_1_svc();
extern int places_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_planeListRet (XDR *, planeListRet*);
extern  bool_t xdr_airports (XDR *, airports*);
extern  bool_t xdr_position (XDR *, position*);

#else /* K&R C */
extern bool_t xdr_planeListRet ();
extern bool_t xdr_airports ();
extern bool_t xdr_position ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
