/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"

planeListRet *
getairports_1_svc(position *argp, struct svc_req *rqstp)
{
	static planeListRet  result;

	/*
	 * insert server code here
	 */

	return &result;
}
