/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "places.h"

bool_t
xdr_portInfo (XDR *xdrs, portInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placeInfo (XDR *xdrs, placeInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airports (XDR *xdrs, airports *objp)
{
	register int32_t *buf;

	 if (!xdr_placeInfo (xdrs, &objp->p))
		 return FALSE;
	 if (!xdr_portInfo (xdrs, &objp->port1))
		 return FALSE;
	 if (!xdr_portInfo (xdrs, &objp->port2))
		 return FALSE;
	 if (!xdr_portInfo (xdrs, &objp->port3))
		 return FALSE;
	 if (!xdr_portInfo (xdrs, &objp->port4))
		 return FALSE;
	 if (!xdr_portInfo (xdrs, &objp->port5))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_planeListRet (XDR *xdrs, planeListRet *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_airports (xdrs, &objp->planeListRet_u.airp))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
