# C++

CC = $(CXX)

# Parameters

CLIENT1 = client
SERVER1 = places

SOURCES_CLNT1.c = 
SOURCES_CLNT1.h = 
SOURCES_SVC1.c = 
SOURCES_SVC1.h =
SOURCES1.x = plane.x

TARGETS_SVC1.c = places_xdr.c plane_svc.c plane_server.c plane_xdr.c places_clnt.c xdrlist.c
TARGETS_CLNT1.c = plane_clnt.c plane_client.c plane_xdr.c xdrlist.c
TARGETS1 = places.h plane.h plane_xdr.c plane_clnt.c plane_svc.c plane_client.c plane_server.c

OBJECTS_CLNT1 = $(SOURCES_CLNT1.c:%.c=%.o) $(TARGETS_CLNT1.c:%.c=%.o)
OBJECTS_SVC1 = $(SOURCES_SVC1.c:%.c=%.o) $(TARGETS_SVC1.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl
RPCGENFLAGS = 

# Targets 

all : $(CLIENT1) $(SERVER1)

$(OBJECTS_CLNT1) : $(SOURCES_CLNT1.c) $(SOURCES_CLNT1.h) $(TARGETS_CLNT1.c) 

$(OBJECTS_SVC1) : $(SOURCES_SVC1.c) $(SOURCES_SVC1.h) $(TARGETS_SVC1.c) 

$(CLIENT1) : $(OBJECTS_CLNT1) 
	$(LINK.c) -o $(CLIENT1) $(OBJECTS_CLNT1) $(LDLIBS) 

$(SERVER1) : $(OBJECTS_SVC1) 
	$(LINK.c) -o $(SERVER1) $(OBJECTS_SVC1) $(LDLIBS)

# This is a template Makefile generated by rpcgen

# Parameters

CLIENT2 = places
SERVER2 = airports

SOURCES_CLNT2.c = 
SOURCES_CLNT2.h = 
SOURCES_SVC2.c = 
SOURCES_SVC2.h = 
SOURCES2.x = places.x

TARGETS_SVC2.c = places_svc.c places_server.c places_xdr.c xdrlist.c
TARGETS_CLNT2.c = places_clnt.c places_client.c places_xdr.c 
TARGETS2 = places.h places_xdr.c places_clnt.c places_svc.c places_client.c places_server.c

OBJECTS_CLNT2 = $(SOURCES_CLNT2.c:%.c=%.o) $(TARGETS_CLNT2.c:%.c=%.o)
OBJECTS_SVC2 = $(SOURCES_SVC2.c:%.c=%.o) $(TARGETS_SVC2.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl
RPCGENFLAGS = 

# Targets 

all : $(SERVER2)

$(OBJECTS_SVC2) : $(SOURCES_SVC2.c) $(SOURCES_SVC2.h) $(TARGETS_SVC2.c) 

$(SERVER2) : $(OBJECTS_SVC2) 
	$(LINK.c) -o $(SERVER2) $(OBJECTS_SVC2) $(LDLIBS)

 clean:
	 $(RM) core $(TARGETS2) $(OBJECTS_CLNT2) $(OBJECTS_SVC2) $(CLIENT2) $(SERVER2)
	 $(RM) core $(TARGETS1) $(OBJECTS_CLNT1) $(OBJECTS_SVC1) $(CLIENT1) $(SERVER1)